
function getRandomElem(names_list) {
    const index = parseInt(Math.random() * names_list.length);
    return shuffle(names_list)[index];
}

function generateName() {
    const suggestions = {};
    suggestions['firstnames'] = new Array(
        'Aaliyah', 'Abbie', 'Abigail', 'Aimee', 'Aisha', 'Alex', 'Alexandra', 'Alice', 'Alicia', 'Alisha', 'Alyssa', 'Amanda', 'Amber', 'Amelia', 'Amy', 'Angela', 'Anna', 'Annabel', 'Annabelle', 'Annie', 'Anya', 'April', 'Ava', 'Beatrice', 'Beth', 'Bethan', 'Bethany', 'Bonnie', 'Brooke', 'Caitlin', 'Cara', 'Casey', 'Catherine', 'Cerys', 'Charley', 'Charlie', 'Charlotte', 'Chelsea', 'Chloe', 'Christina', 'Clara', 'Connie', 'Courtney', 'Crystal', 'Daisy', 'Danielle', 'Darcy', 'Deborah', 'Demi', 'Diana', 'Ebony', 'Eden', 'Edith', 'Eleanor', 'Elena', 'Elise', 'Eliza', 'Elizabeth', 'Ella', 'Ellen', 'Ellie', 'Eloise', 'Elsie', 'Emilia', 'Emily', 'Emma', 'Erin', 'Esme', 'Esther', 'Eva', 'Eve', 'Evelyn', 'Evie', 'Faith', 'Fannie', 'Fatima', 'Faye', 'Ffion', 'Florence', 'Frances', 'Francesca', 'Freya', 'Gabriella', 'Gabrielle', 'Georgia', 'Georgina', 'Grace', 'Hannah', 'Harriet', 'Hazel', 'Heather', 'Heidi', 'Hollie', 'Holly', 'Imogen', 'India', 'Isabel', 'Isabella', 'Isabelle', 'Isla', 'Isobel', 'Jade', 'Jamie', 'Jasmine', 'Jemima', 'Jenna', 'Jennifer', 'Jessica', 'Jessie', 'Joel', 'Josephine', 'Julia', 'Kate', 'Katherine', 'Kathleen', 'Kathryn', 'Katie', 'Kayla', 'Kayleigh', 'Keira', 'Kelly', 'Kelsey', 'Kiera', 'Lara', 'Laura', 'Lauren', 'Layla', 'Leah', 'Lena', 'Libby', 'Lillian', 'Lillie', 'Lilly', 'Lily', 'Lisa', 'Lois', 'Lola', 'Lottie', 'Louise', 'Lucy', 'Lydia', 'Maddison', 'Madeleine', 'Madison', 'Mae', 'Maisie', 'Margaret', 'Margie', 'Maria', 'Marie', 'Martha', 'Mary', 'Maryam', 'Matilda', 'Max', 'Maya', 'Megan', 'Melissa', 'Mia', 'Michelle', 'Millie', 'Mollie', 'Molly', 'Morgan', 'Nancy', 'Nannie', 'Naomi', 'Natalie', 'Natasha', 'Niamh', 'Nicole', 'Olivia', 'Paige', 'Patricia', 'Phoebe', 'Poppy', 'Rachel', 'Rebecca', 'Rhonda', 'Robyn', 'Rosa', 'Rose', 'Rosie', 'Ruby', 'Ruth', 'Sadie', 'Samantha', 'Sara', 'Sarah', 'Savannah', 'Scarlett', 'Shannon', 'Skye', 'Sofia', 'Sophia', 'Sophie', 'Stella', 'Stephanie', 'Summer', 'Tara', 'Taylor', 'Tegan', 'Tia', 'Tiffany', 'Tilly', 'Tommy', 'Traci', 'Tyler', 'Vanessa', 'Velma', 'Victoria', 'Willie', 'Yasmin', 'Zahra', 'Zainab', 'Zara', 'Zoe', 'Belinda',
        'Aaron', 'Abdul', 'Abdullah', 'Adam', 'Ahmed', 'Alan', 'Albert', 'Alex', 'Alexander', 'Alfred', 'Andrew', 'Anthony', 'Archie', 'Arthur', 'Austin', 'Ben', 'Benjamin', 'Bradley', 'Brandon', 'Brian', 'Brooke', 'Caleb', 'Callum', 'Carl', 'Casey', 'Charles', 'Charley', 'Charlie', 'Christian', 'Christopher', 'Cole', 'Connor', 'Conor', 'Craig', 'Curtis', 'Daniel', 'Danny', 'Darcy', 'David', 'Dean', 'Declan', 'Dennis', 'Dewey', 'Dominic', 'Douglas', 'Ebony', 'Eddie', 'Eden', 'Edward', 'Edwin', 'Elena', 'Eliza', 'Eric', 'Erin', 'Esme', 'Ethan', 'Euan', 'Ewan', 'Faith', 'Frances', 'Frank', 'Fraser', 'Fred', 'Frederick', 'Garfield', 'Gary', 'George', 'Gregory', 'Grover', 'Hamza', 'Harrison', 'Harry', 'Harvey', 'Hassan', 'Henry', 'Homer', 'Hugh', 'Hugo', 'Ibrahim', 'Isaac', 'Jack', 'Jackson', 'Jacob', 'Jade', 'Jake', 'James', 'Jamie', 'Jared', 'Jason', 'Jasper', 'Jenna', 'Jeremy', 'Jessie', 'Jimmy', 'Joe', 'Joel', 'John', 'Johnny', 'Jonathan', 'Joseph', 'Josh', 'Joshua', 'Julia', 'Justin', 'Kelly', 'Kelsey', 'Kenneth', 'Kevin', 'Kyle', 'Lara', 'Lawrence', 'Leo', 'Leon', 'Leonard', 'Lewis', 'Liam', 'Lloyd', 'Louis', 'Lucas', 'Luis', 'Luke', 'Maddison', 'Madison', 'Mae', 'Marcus', 'Mark', 'Martin', 'Matthew', 'Max', 'Maximilian', 'Maxwell', 'Maya', 'Michael', 'Miles', 'Mitchell', 'Mohamed', 'Mohammad', 'Mohammed', 'Morgan', 'Muhammad', 'Muhammed', 'Myles', 'Nathan', 'Nathaniel', 'Nicholas', 'Noah', 'Oliver', 'Omar', 'Oscar', 'Owen', 'Patrick', 'Paul', 'Peter', 'Philip', 'Phillip', 'Ralph', 'Raymond', 'Reuben', 'Rhys', 'Richard', 'Robert', 'Robyn', 'Roosevelt', 'Roy', 'Russell', 'Ryan', 'Samuel', 'Sara', 'Scott', 'Sean', 'Sebastian', 'Seth', 'Shannon', 'Skye', 'Sonny', 'Stanley', 'Stella', 'Stephen', 'Steven', 'Taylor', 'Tegan', 'Theo', 'Theodore', 'Thomas', 'Tia', 'Timothy', 'Tobias', 'Tom', 'Tommy', 'Travis', 'Tristan', 'Tyler', 'Victor', 'Vincent', 'Walter', 'Warren', 'Will', 'William', 'Willie', 'Yusuf', 'Zac', 'Zachary', 'Zack', 'Zak', 'Tristan',
        'Adib', 'Alan', 'Albert', 'Alexander', 'Alfred', 'Alvin', 'Andrew', 'Angelo', 'Angelus', 'Anil', 'Anthony', 'Anton', 'Anuj', 'Ardal', 'Arlen', 'Augustus', 'Barry', 'Benito', 'Bob', 'Brandan', 'Brendan', 'Brian', 'Bronislaw', 'Bryan', 'Burt', 'Carl', 'Charles', 'Charlie', 'Christian', 'Christophe', 'Christopher', 'Claude', 'Claudius', 'Cliff', 'Cosmo', 'Cristiano', 'Damian', 'Daniel', 'David', 'Dean', 'Denis', 'Dennis', 'Derek', 'Donald', 'Edward', 'Emil', 'Emiliano', 'Emmanuel', 'Ernest', 'Esteban', 'Eugene', 'Farzan', 'Faust', 'Faustino', 'Fernando', 'Freddie', 'Frederick', 'Gary', 'George', 'Gerald', 'Hassan', 'Helge', 'Henry', 'Islay', 'Jakob', 'James', 'Jamil', 'Jenkins', 'Jim', 'Jimi', 'Joe', 'Johnny', 'Joseph', 'Juan', 'Judah', 'Judith', 'Judy', 'Julio', 'Julius', 'Justin', 'Keith', 'Kevin', 'Khalil', 'Laurence', 'Leon', 'Leonardo', 'Lewis', 'Liam', 'Louis', 'Marc', 'Marcello', 'Mario', 'Mark', 'Martin', 'Marvin', 'Matt', 'Matthew', 'Maurice', 'Maximus', 'Melvin', 'Michael', 'Mike', 'Neil', 'Nicholas', 'Nick', 'Nicolas', 'Nigel', 'Norman', 'Oliver', 'Paul', 'Peter', 'Philip', 'Robert', 'Ryan', 'Sean', 'Sebastian', 'Simon', 'Sophus', 'Stephen', 'Steve', 'Stevie', 'Taurus', 'Terika', 'Theodore', 'Tom', 'Tony', 'Tyr', 'Vasiliy', 'Victor', 'Wilhelm', 'William', 'Yaroslav', 'Zlatan', 'Adiba', 'Alaina', 'Alana', 'Alanis', 'Alannah', 'Alberte', 'Alessa', 'Alessandra', 'Sandra', 'Zandra', 'Alfreda', 'Elfreda', 'Freda', 'Elvina', 'Andrea', 'Andreia', 'Andrina', 'Ann', 'Angelina', 'Angela', 'Angie', 'Aniela', 'Anila', 'Antoinette', 'Antonia', 'Antonina', 'Anuja', 'Ardala', 'Arlene', 'Augustina', 'Barrie', 'Benita', 'Bobby', 'Brenda', 'Brenna', 'Briana', 'Brianna', 'Bryna', 'Bronislava', 'Bryany', 'Bertha', 'Carla', 'Carlene', 'Carly', 'Carrie', 'Charlene', 'Charlize', 'Sharlene', 'Christel', 'Christina', 'Kirsti', 'Kristina', 'Kristy', 'Stina', 'Christine', 'Claudette', 'Klaudie', 'Cleva', 'Cosima', 'Cosma', 'Cristina', 'Cristine', 'Damiana', 'Danette', 'Daniela', 'Danielle', 'Danita', 'Dayna', 'Davida', 'Davina', 'Deanna', 'Deeanna', 'Denise', 'Denisa', 'Dericka', 'Donalda', 'Donella', 'Donna', 'Edwarda', 
        'Emelie', 'Emilia', 'Miliana', 'Emmanuella', 'Emmanuelle', 'Erna', 'Estebana', 'Eugina', 'Genie', 'Farzaneh', 'Faustine', 'Faustina', 'Fernanda', 'Fredrica', 'Fredrika', 'Garyn', 'Georgie', 'Geraldine', 'Jerica', 'Hasna', 'Hella', 'Etta', 'Harriet', 'Hattie', 'Hennie', 'Henrietta', 'Henrika', 'Jetta', 'Isla', 'Jakoba', 'Jaime', 'Jaimi', 'Jamesina', 'Jamia', 'Jamilyn', 'Djamila', 'Jennifer', 'Jemima', 'Jo', 'Janey', 'Janie', 'Fifi', 'Josephe', 'Josephine', 'Posy', 'Juana', 'Judith', 'Judy', 'Jude', 'Julia', 'Giulia', 'Juliana', 'Justeen', 'Justeene', 'Justine', 'Justyne', 'Keitha', 'Kevia', 'Khalila', 'Laurie', 'Leona', 'Leondra', 'Leondrea', 'Leonela', 'Louise', 'Wilhelmina', 'Louella', 'Lovisa', 'Lulu', 'Marcia', 'Celina', 'Marcelina', 'Mary', 'Marcie', 'Martina', 'Martine', 'Marva', 'Marvina', 'Mathilda', 'Mathilde', 'Matilda', 'Matilde', 'Maurisa', 'Maxima', 'Maxine', 'Melissa', 'Michaela', 'Michelle', 'Nelly', 'Nicia', 'Nicole', 'Nicoletta', 'Nicolette', 'Nikol', 'Nikolett', 'Nikolia', 'Nicola', 'Nigella', 'Norma', 'Olivia', 'Paula', 'Paulina', 'Pauline', 'Pavlina', 'Peta', 'Petra', 'Petrina', 'Filippa', 'Philippa', 'Roberta', 'Rihanna', 'Ryana', 'Ryanne', 'Shawna', 'Sebastia', 'Simone', 'Sofia', 'Sophie', 'Stephanie', 'Steph', 'Stephie', 'Taura', 'Teresa', 'Fedora', 'Thea', 'Theodora', 'Tam', 'Tammy', 'Thomasina', 'Toni', 'Thyra', 'Vasilisa', 'Latoya', 'Toya', 'Victorine', 'Vitoria', 'Wilma', 'Guillelmina', 'Yaroslava', 'Zlata', 'Zlatica', 'Sue'
    );
    suggestions['surnames'] = new Array('Adams', 'Alexander', 'Allen', 'Alvarez', 'Anderson', 'Andrews', 'Armstrong', 'Arnold', 'Bailey', 'Baker', 'Barnes', 'Bell', 'Bennett', 'Berry', 'Black', 'Blaese', 'Bradley', 'Brooks', 'Brown', 'Bryant', 'Burns', 'Butler', 'Campbell', 'Carter', 'Castillo', 'Chapman', 'Chavez', 'Clark', 'Cole', 'Coleman', 'Collins', 'Cook', 'Cooper', 'Cox', 'Crawford', 'Cruz', 'Cunningham', 'Davis', 'Diaz', 'Dixon', 'Duncan', 'Dunn', 'Edwards', 'Elliott', 'Ellis', 'Evans', 'Ferguson', 'Fisher', 'Flores', 'Ford', 'Foster', 'Fox', 'Freeman', 'Garcia', 'Gardner', 'Gibson', 'Gonzales', 'Gonzalez', 'Gordon', 'Graham', 'Grant', 'Gray', 'Green', 'Griffin', 'Gutierrez', 'Hall', 'Hamilton', 'Harper', 'Harris', 'Harrison', 'Hart', 'Hawkins', 'Hayes', 'Henderson', 'Henry', 'Hernandez', 'Herrera', 'Hill', 'Holmes', 'Howard', 'Hudson', 'Hughes', 'Hunt', 'Hunter', 'Jackson', 'James', 'Jenkins', 'Jimenez', 'Johnson', 'Johnston', 'Jones', 'Jordan', 'Kelley', 'Kelly', 'Kennedy', 'Kim', 'King', 'Knight', 'Lane', 'Lawrence', 'Lee', 'Lewis', 'Long', 'Lopez', 'Lynch', 'Marshall', 'Martin', 'Mason', 'Matthews', 'Mcdonald', 'Medina', 'Mendoza', 'Meyer', 'Miller', 'Mills', 'Mitchell', 'Moore', 'Morales', 'Morgan', 'Morris', 'Morrison', 'Murphy', 'Murray', 'Nelson', 'Nguyen', 'O\'Brien', 'O\'Connor', 'O\'Doherty', 'O\'Gallagher', 'O\'Moore', 'O\'Neill', 'O\'Quinn', 'O\'Reilly', 'O\'Ryan', 'O\'Sullivan', 'Olson', 'Ortiz', 'Owens', 'Palmer', 'Parker', 'Patel', 'Patterson', 'Payne', 'Perry', 'Phillips', 'Porter', 'Powell', 'Price', 'Ramirez', 'Ramos', 'Reed', 'Reid', 'Reyes', 'Reynolds', 'Rice', 'Richards', 'Richardson', 'Riley', 'Rivera', 'Roberts', 'Robertson', 'Robinson', 'Rodriguez', 'Rogers', 'Romero', 'Rose', 'Ross', 'Ruiz', 'Russell', 'Ryan', 'Sanchez', 'Sanders', 'Scott', 'Shaw', 'Simmons', 'Simpson', 'Smith', 'Snyder', 'Spencer', 'Stephens', 'Stevens', 'Stewart', 'Stone', 'Sullivan', 'Taylor', 'Thomas', 'Thompson', 'Tucker', 'Turner', 'Vasquez', 'Wagner', 'Walker', 'Wallace', 'Walsh', 'Ward', 'Warren', 'Washington', 'Watson', 'Webb', 'Wells', 'West', 'White', 'Williams', 'Willis', 'Wilson', 'Wood', 'Woods', 'Wright', 'Young', 'Trelawney');
    suggestions['fullnames'] = new Array(
        'Elise Butler', 'Hannah Reid', 'Eddie Lee', 'Lillie Jackson', 'Ibrahim Diaz', 'George Cox', 'Darcy Romero', 'Daisy King', 'Caitlin Snyder', 'Jenna Turner', 'Mollie Cruz', 'Paige Hernandez', 'Sara Bradley', 'Tommy Miller', 'Jackson Tucker', 'Grover Palmer', 'Gabrielle Thomas', 'Skye Roberts', 'Adam Blaese', 'Samantha Black', 'Nicholas Scott', 'Eden Sanders', 'Jade Brown', 'Nannie O\'Moore', 'Madison Lynch', 'Annabelle Cunningham', 'Georgina Chavez', 'Theodore Bailey', 'Rose Fisher', 'William Hall', 'Vincent Smith', 'April Murray', 'Madison Hunter', 'Imogen O\'Sullivan', 'Frank Elliott', 'Sean Jones', 'Omar Murphy', 'Lillie Howard', 'Eleanor Ross', 'Niamh Jenkins', 'Warren Anderson', 'Reuben Price', 'Gabriella Ryan', 'Julia Harrison', 'Matthew Bennett', 'Hugo Gray', 'Chloe Holmes', 'Hassan Hart', 'Michelle Morrison', 'Mohammad Morris', 'Kevin Lawrence', 'Alexander Gibson', 'Dennis Webb', 'Anna Willis', 'Ella Patterson', 'Erin Grant', 'Lydia Graham', 'Poppy Patel', 'Isabella Gonzalez', 'Maxwell Nelson', 'Fraser Dunn', 'Alexandra Ramos', 'Annabel Riley', 'Samantha Gutierrez', 'Holly Brooks', 'Skye Wilson', 'Jamie Mason', 'Hugh Hunt', 'Taylor Stewart', 'Tobias Nguyen', 'Gabriella Kelly', 'Muhammed Sullivan', 'Tilly Hill', 'Marie Freeman', 'Christopher Washington', 'Darcy Richards', 'Jackson Garcia', 'Sadie Allen', 'Mia Warren', 'Harrison Chapman', 'Jade Armstrong', 'Joshua Harris', 'Frank Mitchell', 'Freya White', 'Craig Wells', 'Edward Rogers', 'Lloyd Stevens', 'Matilda O\'Ryan', 'Traci Johnston', 'Tia Reed', 'James Long', 'Sara Mills', 'Rosa Woods', 'Olivia Edwards', 'Charles Green', 'Amy Johnson', 'Morgan James', 'Tegan Perry', 'Maya O\'Gallagher', 'Isobel O\'Quinn', 'Imogen Adams', 'Skye Jordan', 'Declan Kim', 'Leonard Wright', 'Nancy Wagner', 'Margie O\'Brien', 'Alyssa O\'Doherty', 'Christian Duncan', 'Joshua Robertson', 'Tara Bell', 'Casey Alvarez', 'Kayla Reyes', 'Traci Harper', 'Joe Russell', 'Mohammed Davis', 'Kiera Shaw', 'Grover Robinson', 'Katherine Evans', 'Maddison Arnold', 'Tommy Rivera', 'Alexandra Griffin', 'Tommy Kelley', 'Marie Ramirez', 'Ben Hayes', 'Hollie Barnes', 'Tara Carter', 'Fred Ford', 
        'Roosevelt O\'Neill', 'Kathleen Mcdonald', 'Charley Henderson', 'Christopher Owens', 'Theo Morales', 'Aaliyah Mendoza', 'Joshua Castillo', 'Tommy Jimenez', 'Joel Powell', 'Joel Flores', 'Ibrahim Ferguson', 'Angela Wood', 'Faye Walsh', 'Brooke Cole', 'Jessie Kennedy', 'Leo Gonzales', 'Tommy Medina', 'Michael Rose', 'Lillie Burns', 'Katherine Berry', 'Tara Foster', 'Heather Hughes', 'Charlie Spencer', 'Nathaniel Knight', 'Aisha Phillips', 'Alexander Lopez', 'Gary Watson', 'Joe Taylor', 'Vincent Hudson', 'Layla Gardner', 'Robert O\'Reilly', 'Lois Cooper', 'Adam Reynolds', 'Lloyd Simpson', 'Charley Cook', 'Nicole Dixon', 'Nathaniel Meyer', 'Tristan Walker', 'Joel Sanchez', 'Matilda Payne', 'Liam Campbell', 'Angela Fox', 'Frances Vasquez', 'Daisy Ward', 'Annie Stephens', 'Dewey Ellis', 'Caleb Morgan', 'Zara Marshall', 'Joel Martin', 'Sophia Rice', 'Keira O\'Connor', 'Sadie Matthews', 'Rebecca Lewis', 'Amanda Herrera', 'Sara West', 'Esme Coleman', 'Alfred Rodriguez', 'Maddison Hamilton', 'Marie Gordon', 'Frank Henry', 'Hassan Bryant', 'Lisa Alexander', 'Nannie Ortiz', 'Cerys Baker', 'Zac Hawkins', 'Tegan Stone', 'Casey Lane', 'Luke Wallace', 'Nicole Crawford', 'Esme Williams', 'Evie Porter', 'Abbie Parker', 'April Moore', 'Ellie Simmons', 'Archie Richardson', 'Kevin Clark', 'Eva Olson', 'Sara Ruiz', 'Freya Thompson', 'Olivia Young', 'Fred Bloggs'
    );
    

    suggestions['rock_star'] = new Array('Prince','Bob Dylan','Madonna','Elvis Presley','Jimi Hendrix','David Bowie','Paul McCartney','Keith Richards','Jim Morrison','Jarvis Cocker','Kurt Cobain','Freddie Mercury','Liam Gallagher','Pete Doherty','Ozzy Osbourne','Johnny Cash','Axl Rose','Courtney Love','Debbie Harry','Rihanna','Celine Dion','Whitney Houston','Taylor Swift','Garth Brooks','Billy Joel','Frank Sinatra','Barbra Streisand','Kanye West','Bruce Springsteen','Lady Gaga','Justin Bieber','Rod Stewart','Neil Diamond','Paul McCartney','Janet Jackson','Julio Iglesias','Bryan Adams','James Taylor','Olivia Newton-John','Stevie Wonder','Barry White','George Michael','Tom Petty','Johnny Hallyday','Robbie Williams','Bob Marley','Mike Posner','Rihanna Drake','Justin Timberlake','James Arhur','Alan Walker');	
    suggestions['film_star'] = new Array('Brad Pitt','Bruce Willis','Angelina Jolie','Matthew Goode','Uma Thurman','Nicole Kidman','Tom Cruise','Ryan Renolds','Felicity Jones','Simon Pegg','Courtney Cox','Kevin Spacey','James Spader','Zach Braff','Isla Fisher','Carrie Fisher','Fred Astaire', 'Humphrey Bogart', 'Marlon Brando', 'James Cagney', 'Charles Chaplin', 'Gary Cooper', 'James Dean', 'Kirk Douglas', 'Henry Fonda', 'Clark Gable', 'Cary Grant', 'William Holden', 'Buster Keaton', 'Gene Kelly', 'Burt Lancaster', 'Robert Mitchum', 'Laurence Olivier', 'Gregory Peck', 'Sidney Poitier', 'Edward Robinson', 'James Stewart', 'Spencer Tracy', 'John Wayne', 'Orson Welles', 'Lauren Bacall', 'Ingrid Bergman', 'Claudette Colbert', 'Joan Crawford', 'Bette Davis', 'Marlene Dietrich', 'Greta Garbo', 'Ava Gardner', 'Judy Garland', 'Lillian Gish', 'Jean Harlow', 'Rita Hayworth', 'Audrey Hepburn', 'Katharine Hepburn', 'Grace Kelly', 'Vivien Leigh', 'Carole Lombard', 'Sophia Loren', 'Marilyn Monroe', 'Mary Pickford', 'Ginger Rogers', 'Barbara Stanwyck', 'Elizabeth Taylor', 'Shirley Temple', 'Mae West','Dwayne Johnson', 'Jackie Chan', 'Matt Damon', 'Tom Cruise', 'Johnny Depp', 'Jennifer Lawrence', 'Ben Affleck', 'Vin Diesel', 'Melissa McCarthy', 'Shah Rukh Khan', 'Robert Downey Jr', 'Akshay Kumar', 'Brad Pitt', 'Adam Sandler', 'Mark Wahlberg', 'Salman Khan', 'Leonardo Dicaprio', 'Chris Pratt', 'Scarlett Johansson', 'Will Smith', 'Amitabh Bachchan', 'Jennifer Aniston', 'Matthew McConaughey', 'Fan Bingbing', 'Harrison Ford', 'Charlize Theron', 'Amy Adams', 'Julia Roberts', 'Mila Kunis', 'Deepika Padukone');	
    suggestions['sports_star'] = new Array('Zlatan Ibrahimovic','Cristiano Ronaldo','Muhammad Ali','Serena Williams','Martina Navratilova','Lionel Messi','David Beckham', 'Ian Black', 'Ian Botham', 'David Broome', 'Joe Calzaghe', 'Mark Cavendish', 'Christopher Chataway', 'Linford Christie', 'Sebastian Coe', 'Henry Cooper', 'Robin Cousins', 'Steve Cram', 'John Curry', 'Steve Davis', 'Christopher Dean', 'Jonathan Edwards', 'Nick Faldo', 'Andrew Flintoff', 'Brendan Foster', 'Paul Gascoigne', 'Ryan Giggs', 'Lewis Hamilton', 'David Hemery', 'Damon Hill', 'Kelly Holmes', 'Chris Hoy', 'Dorothy Hyman', 'Ann Jones', 'Jim Laker', 'Lennox Lewis', 'Anita Lonsbrough', 'Nigel Mansell', 'Liz McColgan', 'Tony McCoy', 'Barry McGuigan', 'Bobby Moore', 'Stirling Moss', 'Andy Murray', 'Steve Ovett', 'Michael Owen', 'Mary Peters', 'Gordon Pirie', 'Paula Radcliffe', 'Mary Rand', 'Steve Redgrave', 'Dai Rees', 'Greg Rusedski', 'Tom Simpson', 'David Steele', 'Jackie Stewart', 'John Surtees', 'Daley Thompson', 'Zara Tindall', 'Jayne Torvill', 'Virginia Wade', 'Fatima Whitbread', 'Bradley Wiggins', 'Jonny Wilkinson');	
    suggestions['tv_character'] = new Array('Mickey Mouse','Kermit the Frog','Miss Piggy','Big Bird','Gonzo','The Fonz','Homer Simpson','Marge Simpson','Bart Simpson','Dale Cooper','Tony Soprano','Fox Mulder','Dana Scully','Eric Cartman','Captain Kirk','Chandler Bing','Gob Bluth','Frasier Crane','Niles Crane','Peppa Pig');	
	suggestions['criminal'] = new Array('Al Capone','Charles Manson','Ted Kaczynski','Tom Horn','Adam Lanza','Ted Bundy','Jack the Ripper','Ronnie Kray','Reggie Kray','Harold Shipman','Darth Vadar','Tommy DeVito','Keyser Soze','Frank Booth','Alex DeLarge','Norman Bates');	
	suggestions['celebrity'] = new Array('Johnny Depp','David Beckham','Donald Trump','Hilary Clintonn','Margaret Thatcher','Paul McCartney','Dustin the Turkey','David Bowie','Jack Duckworth','Cliff Richard','Julie Andrews','J.K. Rowling','Richard Branson','Harold Bishop','Adam Sandler','Brad Pitt','Jack Nicholson','Keanu Reeves','Michael Caine','Orlando Bloom','Will Smith','Tom Cruise','Teri Hatcher','Paris Hilton','Big Bird','Natalie Portman','Kermit the Frog','Kim Kardashian','Anthony Hopkins','Tom Cruise','Rihanna','Yogi Bear','Luke Skywalker','Bart Simpson','Indiana Jones','Robin Hood','Ronald McDonald','George Bush','Tony Blair','Rio Ferdinand','Wayne Rooney','Ricky Gervais','Steve Merchant','James Corden','Stephen Hawking','Richard Dawkins','Boris Johnson','Albert Einstein','Michael Palin','Walter Raleigh','Trevor MacDonald','Stephen Fry');

    const all_props = Object.getOwnPropertyNames(suggestions);
    const index = getRandomElem(all_props);
    var name = getRandomElem(suggestions[index]);
    if(all_props[index] === 'firstnames') {
        name += getRandomElem(suggestions['surnames']);
    } else if(all_props[index] === 'surnames') {
        name = getRandomElem(suggestions['firstnames']) + name;
    }

    return name.split(' ').join('').toLowerCase() + ('000'+Math.random()*1000).slice(-3);
}

function generateRoomName() {
    const suggestions = {};
    suggestions['people_group'] = new Array ('cowboys','Yankees','vikings','hotspurs','warriors','saints','raiders','buccaneers','pirates','cardinals', 'angels', 'rangers','wanderers','giants','patriots','titans','independents','dodgers','flyers','mariners','twins','senators','metropolitans');
    suggestions['group'] = new Array('builders','pixies','plumbers','zombies','sprites','doctors','jockies','preachers','students','singers','rappers','spacemen','goblins','surgeons','nurses','policemen','firemen','teachers','librarians','footballers','vandals','street artists','painters');	
    
    suggestions['species'] = new Array(
        'werewolf','vampire','mermaid','wizard',	'angel','demon','alien','ghost','loch ness monster','phantom cat',
        'goblin','pixie','unicorn','yeti','gremlin','zombie','dragon','serpent','fairy','elf','fallen angel',
        'gargoyle', 'siren', 'shape shifter', 'yeti'
    );
    suggestions['verb'] = new Array('singing','kissing','dancing','laughing','swinging','joking','acting','skipping','flying','snuggling','collapsing','walking','running','smiling','punching','kicking','drinking','smoking','loving','munching','bashing','crashing','running','sailing','spinning','working','shouting','smooching','prancing','bouncing','juggling','skipping','daring','complaining');
    suggestions['phys_adj'] = new Array(
        'pretty', 'charming', 'handsome', 'beautiful', 'sticky', 'curvaceous', 'curvy', 'ample', 'pleasing', 'smooth', 'adorable','perfect',
        'sloppy','slimy','spiky','greasy','scrawny', 'wobbly', 'fragile', 'hairy', 'grubby',  'ugly',  'sticky', 'ruddy',
        'passionate','sizzling','magical','tender','sensational','frantic','deep', 'important', 'splendid', 'incredible', 'hot'
    );

    const keys = Object.getOwnPropertyNames(suggestions);


    const name_start_arr = suggestions[ keys[parseInt(Math.random()*3+2)] ]
    const name_start_index = parseInt(Math.random() * name_start_arr.length)
    const name_end_arr = suggestions[ keys[parseInt(Math.random()*2)] ]
    const name_end_index = parseInt(Math.random() * name_end_arr.length);
    
    const roomname = name_start_arr[name_start_index] + name_end_arr[name_end_index];

    return roomname;
}

function shuffle(o){ 
    for(var j, x, i = o.length; i; j = parseInt(Math.random() * i), x = o[--i], o[i] = o[j], o[j] = x);
    return o;
}

module.exports.generateName = generateName;
module.exports.generateRoomName = generateRoomName;
module.exports.shuffle = shuffle;
